'use strict';

exports = module.exports = {
    auth0: require('./auth0'),
    azuread: require('./azuread'),
    bitbucket: require('./bitbucket'),
    dropbox: require('./dropbox'),
    facebook: require('./facebook'),
    fitbit: require('./fitbit'),
    foursquare: require('./foursquare'),
    github: require('./github'),
    gitlab: require('./gitlab'),
    googleplus: require('./googleplus'),
    google: require('./google'),
    instagram: require('./instagram'),
    linkedin: require('./linkedin'),
    live: require('./live'),
    medium: require('./medium'),
    nest: require('./nest'),
    slack: require('./slack'),
    twitter: require('./twitter'),
    vk: require('./vk'),
    yahoo: require('./yahoo'),
    arcgisonline: require('./arcgisonline'),
    phabricator: require('./phabricator'),
    reddit: require('./reddit'),
    meetup: require('./meetup'),
    tumblr: require('./tumblr'),
    twitch: require('./twitch'),
    salesforce: require('./salesforce'),
    wordpress: require('./wordpress'),
    office365: require('./office365'),
    pinterest: require('./pinterest'),
    pingfed: require('./pingfed'),
    discord: require('./discord')
};
