'use strict';

const internals = {};


exports = module.exports = {
    arcgisonline: require('./arcgisonline'),
    auth0: require('./auth0'),
    azure: require('./azure'),
    'azure-legacy': require('./azure-legacy'),
    bitbucket: require('./bitbucket'),
    cognito: require('./cognito'),
    digitalocean: require('./digitalocean'),
    discord: require('./discord'),
    dropbox: require('./dropbox'),
    facebook: require('./facebook'),
    fitbit: require('./fitbit'),
    foursquare: require('./foursquare'),
    github: require('./github'),
    gitlab: require('./gitlab'),
    google: require('./google'),
    googleplus: require('./googleplus'),
    instagram: require('./instagram'),
    linkedin: require('./linkedin'),
    live: require('./live'),
    medium: require('./medium'),
    meetup: require('./meetup'),
    mixer: require('./mixer'),
    nest: require('./nest'),
    okta: require('./okta'),
    phabricator: require('./phabricator'),
    pingfed: require('./pingfed'),
    pinterest: require('./pinterest'),
    reddit: require('./reddit'),
    salesforce: require('./salesforce'),
    slack: require('./slack'),
    spotify: require('./spotify'),
    stripe: require('./stripe'),
    trakt: require('./trakt'),
    tumblr: require('./tumblr'),
    twitch: require('./twitch'),
    twitter: require('./twitter'),
    vk: require('./vk'),
    wordpress: require('./wordpress'),
    yahoo: require('./yahoo')
};
